### ISSUE TITLE
Proposing new project name

### ISSUE THREAD

**Issue by thody** [normative/generator-hapi-service#14]
I'd like to propose we go with a more generic name since we plan to open source this. Also, I'd like the name to reflect that this generator is tailored to creating projects for APIs, as opposed to full-stack apps (no view support, for example).

I'm thinking something like `generator-hapi-service`.

**Comment by michaelryancaputo** [comment]
Sounds good to me.

**Comment by thody** [comment]
Cool, I'll do it up.

**Comment by thody** [comment]
Is anything required to update the name on the Yeoman generator directory? http://yeoman.io/generators/

**Comment by michaelryancaputo** [comment]
I can't remember, i'm not on my work machine at the moment, I think this is the process: https://docs.npmjs.com/cli/version

**Comment by thody** [comment]
:metal:
